### PR TITLE
use bblfsh-drivers image

### PR DESCRIPTION
**Pull request by smacker**
Fix: #67

### CODE REVIEW

**Comment by carlosms** [comment]
I would image that with `-drivers` image we would also remove the drivers installation.

As it is now, if we are using the bigger image, and still re-install all drivers, does it make sense? Are we not worsening the current situation?

**Comment by smacker** [comment]
I'm not sure I understand your concern. I did quick test and it worked as expected. (slowly download bblfsh-drivers image and then install all drivers except cpp super quick)

Could you please provide steps how to reproduce the problem you are talking about.

**Comment by carlosms** [comment]
It was more a question than a bug report. I've done some testing and now I see that even if the driver install call is made for `latest`, the installed drivers are not updated to the latest release, they just return "driver already installed".

**Comment by carlosms** [comment]
What about this comment you made https://github.com/src-d/engine/issues/67#issuecomment-433346503?

> Right now we have very good example of why it's problem:
> We have bblfsh-web v0.8.0 but it can't work with current latest drivers image. Only with a normal one because it requires newer drivers.

If the drivers that ship bundled with bblfsh v2.9.2-drivers are not updated, will this PR break https://github.com/src-d/engine/pull/136?

**Comment by smacker** [comment]
> It was more a question than a bug report. I've done some testing and now I see that even if the driver install call is made for latest, the installed drivers are not updated to the latest release, they just return "driver already installed".

Now I get what you mean. Yes, bblfshd works in the same way as docker. If it has `latest` tag locally it just uses it without checking for a newer one on the remote.

> What about this comment you made #67 (comment)?

it was about version v2.9.0 or v2.8.0, I don't remember which one was the latest for the moment of me writing that comment. v2.9.2 works correctly with bblfsh-web.

**Comment by carlosms** [comment]
great, thanks for confirming it will work fine

**Pull request merged**
