### PR TITLE
Bump changelog for v0.16.0

### PR DESCRIPTION
**Pull request by carlosms**
Updates bblfsh-web and sourced-ui, plus bumps the changelog for v0.16.0

---

* [x] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Review by smacker — APPROVED** [review]

**Review by dpordomingo — APPROVED** [review]
LGTM

But I wonder if it would be nice to expose the major changes of the bumped libs, to avoid the user go to its changelogs to find what relevant changes to expect.

**Comment by dpordomingo** [comment]
for example, I'd mention that:
- xPath UAST filter now works with results that are plain values
- sql lab supports spark query cancellation
- charts uses new color palettes with source{d} brand colors
- smaller `sourced-ui` image size

**Comment by carlosms** [comment]
Good idea. I'd say let's skip for this one, and do for the next releases. Or do it for this 0.16 release, but afterwards.
I think it needs to be a hand-crafted approach instead of just a plain summary of the other changelogs. For example, spark features in sourced-ui are not relevant to sourced-ce users (yet).

**Comment by dpordomingo** [comment]
Agree with your proposal and about the necessity of doing it by hand, to extract only relevant features for the end user.

Also agree with your proposal of doing it for next releases.

**Pull request merged**
