### PR TITLE
Update gitbase to 0.22.0-rc1

### PR DESCRIPTION
**Pull request by carlosms**

### CODE REVIEW

**Review by smacker — APPROVED** [review]

**Comment by smacker** [comment]
oh. let's add prefix.

**Comment by carlosms** [comment]
The prefix is not a typo, it was released without it.

**Comment by carlosms** [comment]
oh there is a tag with `v` now...

**Comment by carlosms** [comment]
Fixed and force-pushed

**Review by se7entyse7en — APPROVED** [review]

**Pull request merged**
