### PR TITLE
Validate params for orgs init

### LINKED ISSUE #59: Add github token and orgs validation
Parent: #47

We need to validate incorrect input early because we can't catch errors when containers are started already.

### PR DESCRIPTION
**Pull request by smacker**
Fix: #59

It's the simplest possible implementation that is good enough for now
and easy to remove later.

Signed-off-by: Maxim Sukharev <max@smacker.ru>

### CODE REVIEW

**Comment by carlosms** [comment]
Is there any downside if we used the regular go-github lib?

**Comment by smacker** [comment]
I didn't use go-github here on purpose to accent that this code is a temporary solution. I truly believe cli shouldn't talk directly to github for orgs and token validation.

**Review by carlosms — APPROVED** [review]
I'm not too happy redoing the code that go-github already does, even if it's a small part.
But we can use it as it is and discuss later how to improve.

**Comment by smacker** [comment]
I'm glad you don't like it so we can remove it after release :)

**Comment by smacker** [comment]
rebased on master. merge after CI pass.

**Pull request merged**
