### PR TITLE
Fix #337 issue

### LINKED ISSUE #337: Malformed input or input contains unmappable characters in engine container
## Expected Behavior
show repository count in Siva file.
To get it: 
```bash
wget http://pga.sourced.tech/siva/latest/d1/d19142e20949d442c20275e467f3d39c33a21f03.siva
```

## Current Behavior
gives an error
```
18/02/28 14:56:52 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/spark-2e156cef-3a14-4ea7-8aaf-21f354ce70dd/processing-repositories/E692B3ECA9BEB2D28AE0357893B0A2DF/d19142e20949d442c20275e467f3d39c33a21f03.siva/refs/heads/fix/25029-roadmap-filters?and-versions-not-visible-new-side-bar-dark-background/01614be7-1d01-8c15-97c1-b29f182aaada
```

## Possible Solution
run in the `srcd/engine-jupyter` container next commands:
```bash
apt-get update
apt-get install -y locales
locale-gen en_US.UTF-8
```

## Steps to Reproduce (for bugs)
```
mkdir siva
cd siva
wget http://pga.sourced.tech/siva/latest/d1/d19142e20949d442c20275e467f3d39c33a21f03.siva\
docker run --name engine-jupyter --rm -it -p 8080:8080 -v $(pwd)/siva:/repositories --link bblfshd:bblfshd srcd/engine-jupyter
```
in jupyter notebook run first cell:
```python
from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "/repositories", "siva")

print("%d repositories successfully loaded" % (engine.repositories.count()/2))
```

I will create a PR with the solution.

### PR DESCRIPTION
**Pull request by zurk**
This PR fix https://github.com/src-d/engine/issues/337 issue, all described there.

### CODE REVIEW

**Comment by zurk** [comment]
Make revert to being sure it is not my fault. ¯\_(ツ)_/¯

**Comment by ajnavarro** [comment]
The main problem is fixed now: https://github.com/src-d/engine/pull/340 . Can you rebase to make tests pass please?

**Comment by zurk** [comment]
ok, just did it. 
As I can see in https://github.com/src-d/engine/pull/340/files
we want to use `pyspark==2.2.1`

So, I think we should make PR to change version here: https://github.com/src-d/infrastructure/blob/master/dockerfiles/spark/Dockerfile#L4 and ask @rporres to deploy it on our cluster.

**Comment by bzz** [comment]
Shall we merge this guy and make a release to publish new engine-jupyter image?

**Comment by zurk** [comment]
@bzz, it is not so important for my current issues, and definitely not urgent, but at some point yes, we should publish it.
So, priority is low.

**Pull request merged**
