### PR TITLE
Simplify Travis config

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Using Xenial -> no need for the toolchain hacks

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@smacker Friendly 28 days ping :)

**Comment by smacker** [comment]
@vmarkovtsev I got the access to approve&merge it like 30 minutes ago :-D

**Comment by smacker** [comment]
The only problem I see with this PR: support for Xenial is still experimental on Travis. For example documentation doesn’t mention it at all.

**Comment by vmarkovtsev** [comment]
@smacker https://github.com/travis-ci/travis-yml/pull/16/files

**Comment by smacker** [comment]
yeah. The name of the PR "Allow **experimental** xenial dist". I experienced unreliable behaviour with this flag in my own project:

Config https://travis-ci.org/smacker/go-tree-sitter/jobs/445374608/config
```
{
  "go": "1.11",
  "os": "linux",
  "dist": "xenial",
  "sudo": false,
  "group": "stable",
  "script": [
    "go test -v ./..."
  ],
  "install": [
    "make",
    "go get -t ./..."
  ],
  "language": "go"
}
```

Logs https://travis-ci.org/smacker/go-tree-sitter/jobs/445374608
```
Build system information
Build language: go
Build group: stable
Build dist: xenial
Build id: 445374606
Job id: 445374608
Runtime kernel version: 4.14.12-041412-generic
travis-build version: 18237616e
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
git version
git version 2.15.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

So it uses `trusty` _sometimes_. Issue about it: https://github.com/travis-ci/travis-ci/issues/10110

**Comment by vmarkovtsev** [comment]
We seem to need `sudo: required`, the support also says that it is the new preferred way.

**Pull request merged**
