### PR TITLE
Fixing documentation of workdirs command

### PR DESCRIPTION
**Pull request by spier**
The command to list all workdirs is:
```
sourced status workdirs
```

Rather than:
```
sourced workdirs
```

---

* [ ] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [x] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Review by dpordomingo — APPROVED** [review]
many thanks @juanjux

**Comment by dpordomingo** [comment]
ouch, can you sign off?

**Comment by dpordomingo** [comment]
ouch, **DCO** bot is complaing :(
could you sign-off your contribution?

**Comment by se7entyse7en** [comment]
Thanks @spier!

**Pull request merged**
