### PR TITLE
docs on raw repos usage, getRemoteReferences added

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by erizocosmico** [comment]
tests fixed

**Comment by erizocosmico** [comment]
@mcarmonaa 👍, I'll add that raw means standard and bare, but I don't know if it's useful to add another example for bare, because the code is exactly the same except for `s/standard/bare/`

**Comment by erizocosmico** [comment]
done @mcarmonaa

**Comment by jfontan** [comment]
I believe it's a bit confusing. You specify "standard" as parameter that means "raw" that include both "standard" and "bare" repos. Is this correct?

**Comment by erizocosmico** [comment]
Nope, raw is a term to refer to both standard and bare (which is not valid as a parameter). Only valid parameters are `standard`, `bare` and `siva`.

For demo purposes, I had to pick one of them and it was `standard`, because both work in the exact same way.

**Comment by jfontan** [comment]
Got it, thanks for the clarification. Somehow I understood that only "standard" and "siva" were allowed as parameter.

**Pull request merged**
