### PR TITLE
[WIP] Add gsc image to docker-compose.yml

### PR DESCRIPTION
**Pull request by carlosms**
part of #207.

### CODE REVIEW

**Comment by smacker** [comment]
remember to add persistent storage to gsc for tables created in spark

**Comment by se7entyse7en** [comment]
If we want to enable also registering pg tables on spark we should also add postgres driver to jvm classpath. [private] https://src-d.slack.com/archives/C7UDG0GP6/p1565942223215000?thread_ts=1565896783.212300&cid=C7UDG0GP6

**Comment by carlosms** [comment]
Update so it does not get lost in minutes and chats: There will be a spark image published with GSC and the postgres drivers included.

About persistence of storage for GSC tables, this needs to be added to this PR: [PRIVATE] https://github.com/src-d/gitbase-spark-connector-enterprise#on-configuring-a-persistent-metastore [PRIVATE] https://github.com/src-d/gitbase-spark-connector-enterprise/pull/121

**Comment by se7entyse7en** [comment]
See [here](https://github.com/src-d/sourced-ui/issues/235#issuecomment-537488079).

**Pull request closed without merging**
