### PR TITLE
ci: fix bblfsh usage in travis

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by jfontan** [comment]
I would keep the commands only in one place. As @mcarmonaa says using make should be enough.

**Comment by erizocosmico** [comment]
Done

**Comment by ajnavarro** [comment]
`time="2017-11-22T16:05:22Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"`

It appears that the make commands creates a server and freezes everything.

**Comment by erizocosmico** [comment]
Should be fixed now.

**Pull request merged**
